/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Capybara :) always will be
 * OpenAPI spec version: 1.0.0
 */

import getUserIndividualPlanMutator from ".././custom-client";

export const getUserIndividualPlan = () => {
  return getUserIndividualPlanMutator<string[]>({
    url: `/api/hono/openapi/user/individual plan`,
    method: "GET",
  });
};

export type GetUserIndividualPlanQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserIndividualPlan>>
>;

