/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Capybara
 * OpenAPI spec version: 1.0.0
 */
import type { GetAuthSession200Data } from './getAuthSession200Data';

export type GetAuthSession200 = {
  data: GetAuthSession200Data;
};
