/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Capybara
 * OpenAPI spec version: 1.0.0
 */
import type { GetGeneralGet200MonthsItemGradesItem } from './getGeneralGet200MonthsItemGradesItem';

export type GetGeneralGet200MonthsItem = {
  grades: GetGeneralGet200MonthsItemGradesItem[];
  name: string;
};
