/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Capybara
 * OpenAPI spec version: 1.0.0
 */

export type GetGeneralGet200MonthsItemGradesItem = {
  CONTROLSHORTNAME: string;
  DAYNUM: string;
  GRADE: string;
  LFP: string;
  MONTHSTR: string;
  RECORDBOOK: string;
};
