/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Capybara
 * OpenAPI spec version: 1.0.0
 */
import type { GetGeneralGet200MonthsItem } from './getGeneralGet200MonthsItem';

export type GetGeneralGet200 = {
  journalName: string;
  months: GetGeneralGet200MonthsItem[];
};
