/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Capybara
 * OpenAPI spec version: 1.0.0
 */
import type { GetJournalGet200MonthsItemGradesItem } from './getJournalGet200MonthsItemGradesItem';

export type GetJournalGet200MonthsItem = {
  grades: GetJournalGet200MonthsItemGradesItem[];
  name: string;
};
