/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Capybara
 * OpenAPI spec version: 1.0.0
 */
import type { GetJournalGrades200ControlsItem } from "./getJournalGrades200ControlsItem";
import type { GetJournalGrades200GradesItem } from "./getJournalGrades200GradesItem";

export type GetJournalGrades200 = {
  controls: GetJournalGrades200ControlsItem[];
  grades: GetJournalGrades200GradesItem[];
  journalName: string;
};
