/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Capybara
 * OpenAPI spec version: 1.0.0
 */

export type GetJournalGrades200GradesItem = {
  CONTROLNAME: string;
  CONTROLSHORTNAME: string;
  DAYNUM: string;
  GRADE: string;
  LFP: string;
  MONTHSTR: string;
  RECORDBOOK: string;
};
