/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Capybara
 * OpenAPI spec version: 1.0.0
 */
import type { GetJournalGet200MonthsItem } from './getJournalGet200MonthsItem';

export type GetJournalGet200 = {
  journalName: string;
  months: GetJournalGet200MonthsItem[];
};
