/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Capybara
 * OpenAPI spec version: 1.0.0
 */

export type GetUserSchedule200ItemType =
  (typeof GetUserSchedule200ItemType)[keyof typeof GetUserSchedule200ItemType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetUserSchedule200ItemType = {
  up: "up",
  bottom: "bottom",
  full: "full",
} as const;
