/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Capybara
 * OpenAPI spec version: 1.0.0
 */

export type GetUserSchedule200ScheduleItemListItem = {
  auditory: string;
  dateFrom: string;
  dateTo: string;
  name: string;
  number: string;
  subjectName: string;
  teacherFullName: string;
  teacherShortName: string;
};
