/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Capybara
 * OpenAPI spec version: 1.0.0
 */

export type GetUserProfile200 = {
  birthDate: string;
  course: string;
  faculty: string;
  group: string;
  name: string;
  recordNumber: string;
  speciality: string;
  surname: string;
};
