/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Capybara
 * OpenAPI spec version: 1.0.0
 */
import type { GetUserSchedule200ItemType } from "./getUserSchedule200ItemType";

export type GetUserSchedule200Item = {
  auditory: string;
  dateFrom: string;
  dateTo: string;
  day: string;
  isSelectable: boolean;
  name: string;
  number: string;
  subjectName: string;
  type: GetUserSchedule200ItemType;
};
