/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Capybara
 * OpenAPI spec version: 1.0.0
 */
import type { GetUserSchedule200ItemType } from './getUserSchedule200ItemType';

export type GetUserSchedule200Item = {
  dateFrom: string;
  dateTo: string;
  day: string;
  name: string;
  number: string;
  type: GetUserSchedule200ItemType;
};
