/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Capybara
 * OpenAPI spec version: 1.0.0
 */

export type GetUserRating200Item = {
  group: string;
  name: string;
  number: string;
  rating: string;
  surname: string;
  type: string;
};
