/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Capybara
 * OpenAPI spec version: 1.0.0
 */
import type { GetUserSchedule200ScheduleItemListItem } from "./getUserSchedule200ScheduleItemListItem";

export type GetUserSchedule200ScheduleItem = {
  date: string;
  list: GetUserSchedule200ScheduleItemListItem[];
  month: string;
  type: string;
  weekDay: string;
};
