/**
 * Generated by orval v7.2.0 🍺
 * Do not edit manually.
 * Capybara
 * OpenAPI spec version: 1.0.0
 */
import type { GetUserSchedule200ScheduleItem } from "./getUserSchedule200ScheduleItem";
import type { GetUserSchedule200UniqueListItem } from "./getUserSchedule200UniqueListItem";

export type GetUserSchedule200 = {
  schedule: GetUserSchedule200ScheduleItem[];
  uniqueList: GetUserSchedule200UniqueListItem[];
};
