/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * Capybara
 * OpenAPI spec version: 1.0.0
 */

export type TestType = typeof TestType[keyof typeof TestType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TestType = {
  top: 'top',
  bottom: 'bottom',
  full: 'full',
} as const;
